import { useState, useMemo } from 'react';

const CRAWLERS = [
  { id: 'all', name: 'All Crawlers', agent: '*' },
  { id: 'google', name: 'Googlebot', agent: 'Googlebot' },
  { id: 'bing', name: 'Bingbot', agent: 'Bingbot' },
  { id: 'gptbot', name: 'GPTBot (ChatGPT)', agent: 'GPTBot' },
  { id: 'ccbot', name: 'CCBot (Common Crawl)', agent: 'CCBot' },
  { id: 'google-ai', name: 'Google-Extended (AI)', agent: 'Google-Extended' },
  { id: 'bytespider', name: 'Bytespider (TikTok)', agent: 'Bytespider' },
];

interface Rule {
  agent: string;
  disallow: string[];
  allow: string[];
}

export default function RobotsTxtGenerator() {
  const [rules, setRules] = useState<Rule[]>([{ agent: '*', disallow: ['/admin/', '/private/'], allow: ['/'] }]);
  const [sitemapUrl, setSitemapUrl] = useState('https://example.com/sitemap.xml');
  const [host, setHost] = useState('https://example.com');
  const [crawlDelay, setCrawlDelay] = useState('');
  const [copied, setCopied] = useState(false);

  const addRule = () => setRules([...rules, { agent: 'Googlebot', disallow: [], allow: ['/'] }]);
  const removeRule = (i: number) => setRules(rules.filter((_, idx) => idx !== i));
  const updateAgent = (i: number, agent: string) => { const n = [...rules]; n[i].agent = agent; setRules(n); };
  const addPath = (i: number, type: 'disallow' | 'allow') => { const n = [...rules]; n[i][type] = [...n[i][type], '/']; setRules(n); };
  const removePath = (i: number, type: 'disallow' | 'allow', pi: number) => { const n = [...rules]; n[i][type] = n[i][type].filter((_, idx) => idx !== pi); setRules(n); };
  const updatePath = (i: number, type: 'disallow' | 'allow', pi: number, val: string) => { const n = [...rules]; n[i][type][pi] = val; setRules(n); };

  const output = useMemo(() => {
    let txt = '# Robots.txt generated by FreeAIToolz.com\n# https://freeaitoolz.com/tools/robots-txt-generator\n\n';
    rules.forEach(rule => {
      txt += `User-agent: ${rule.agent}\n`;
      rule.disallow.forEach(d => { if (d) txt += `Disallow: ${d}\n`; });
      rule.allow.forEach(a => { if (a) txt += `Allow: ${a}\n`; });
      if (crawlDelay) txt += `Crawl-delay: ${crawlDelay}\n`;
      txt += '\n';
    });
    if (sitemapUrl) txt += `Sitemap: ${sitemapUrl}\n`;
    if (host) txt += `Host: ${host}\n`;
    return txt.trim();
  }, [rules, sitemapUrl, host, crawlDelay]);

  const copy = () => { navigator.clipboard.writeText(output); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  const download = () => {
    const blob = new Blob([output], { type: 'text/plain' });
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'robots.txt'; a.click();
  };

  const inputClass = "w-full p-2.5 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none text-sm";

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="space-y-5">
          {/* Global Settings */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-bold text-gray-700 mb-1">Sitemap URL</label>
              <input type="text" value={sitemapUrl} onChange={e => setSitemapUrl(e.target.value)} placeholder="https://example.com/sitemap.xml" className={inputClass} />
            </div>
            <div>
              <label className="block text-sm font-bold text-gray-700 mb-1">Host</label>
              <input type="text" value={host} onChange={e => setHost(e.target.value)} placeholder="https://example.com" className={inputClass} />
            </div>
          </div>

          <div>
            <label className="block text-sm font-bold text-gray-700 mb-1">Crawl Delay (seconds, optional)</label>
            <input type="number" value={crawlDelay} onChange={e => setCrawlDelay(e.target.value)} placeholder="Leave empty for no delay" className={`${inputClass} w-48`} />
          </div>

          {/* Rules */}
          {rules.map((rule, i) => (
            <div key={i} className="bg-gray-50 rounded-xl border border-gray-200 p-4 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-gray-500">Rule {i + 1}</span>
                {rules.length > 1 && <button onClick={() => removeRule(i)} className="text-xs text-red-500 hover:text-red-700 font-bold">Remove</button>}
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-600 mb-1">User-Agent</label>
                <select value={rule.agent} onChange={e => updateAgent(i, e.target.value)} className={inputClass}>
                  {CRAWLERS.map(c => <option key={c.id} value={c.agent}>{c.name} ({c.agent})</option>)}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-600 mb-1">Disallow Paths</label>
                {rule.disallow.map((d, pi) => (
                  <div key={pi} className="flex gap-2 mb-1">
                    <input type="text" value={d} onChange={e => updatePath(i, 'disallow', pi, e.target.value)} className={`${inputClass} flex-1`} placeholder="/path/" style={{fontFamily: "'Space Mono', monospace"}} />
                    <button onClick={() => removePath(i, 'disallow', pi)} className="text-red-400 hover:text-red-600 font-bold px-2">×</button>
                  </div>
                ))}
                <button onClick={() => addPath(i, 'disallow')} className="text-xs font-bold text-red-600 hover:text-red-800">+ Add Disallow</button>
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-600 mb-1">Allow Paths</label>
                {rule.allow.map((a, pi) => (
                  <div key={pi} className="flex gap-2 mb-1">
                    <input type="text" value={a} onChange={e => updatePath(i, 'allow', pi, e.target.value)} className={`${inputClass} flex-1`} placeholder="/" style={{fontFamily: "'Space Mono', monospace"}} />
                    <button onClick={() => removePath(i, 'allow', pi)} className="text-red-400 hover:text-red-600 font-bold px-2">×</button>
                  </div>
                ))}
                <button onClick={() => addPath(i, 'allow')} className="text-xs font-bold text-emerald-600 hover:text-emerald-800">+ Add Allow</button>
              </div>
            </div>
          ))}
          <button onClick={addRule} className="text-sm font-bold text-blue-600 hover:text-blue-800">+ Add Rule for Another Bot</button>
        </div>

        {/* Output */}
        <div>
          <div className="flex justify-between items-center mb-2">
            <label className="text-sm font-bold text-gray-700">Generated robots.txt</label>
            <div className="flex gap-2">
              <button onClick={copy} className="text-xs font-bold px-3 py-1.5 rounded-lg bg-blue-600 text-white hover:bg-blue-700">{copied ? '✓ Copied' : 'Copy'}</button>
              <button onClick={download} className="text-xs font-bold px-3 py-1.5 rounded-lg bg-emerald-600 text-white hover:bg-emerald-700">⬇ Download</button>
            </div>
          </div>
          <pre className="bg-gray-950 text-green-400 p-5 rounded-xl text-sm overflow-auto min-h-[400px] leading-relaxed" style={{fontFamily: "'Space Mono', monospace"}}>{output}</pre>
          <p className="text-xs text-gray-500 mt-2">Upload this file to the root of your website: yourdomain.com/robots.txt</p>
        </div>
      </div>
    </div>
  );
}
