export const prerender = false;

import type { APIRoute } from 'astro';

export const POST: APIRoute = async ({ request }) => {
  try {
    const { text, tone, tool } = await request.json();

    if (!text || !text.trim()) {
      return new Response(JSON.stringify({ error: 'Text is required' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // Rate limiting: max 5000 characters
    if (text.length > 5000) {
      return new Response(JSON.stringify({ error: 'Text must be under 5000 characters' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    const ANTHROPIC_API_KEY = import.meta.env.ANTHROPIC_API_KEY;

    if (!ANTHROPIC_API_KEY) {
      return new Response(JSON.stringify({ error: 'API not configured' }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // Build prompt based on tool type
    let systemPrompt = '';
    let userPrompt = '';

    switch (tool) {
      case 'humanizer':
        systemPrompt = 'You are an expert text humanizer. You rewrite AI-generated text to sound completely natural and human-written.';
        userPrompt = `Rewrite the following text to sound completely natural and human-written.

Tone: ${tone || 'standard'}

Rules:
- Remove all AI-sounding patterns (overly formal transitions, repetitive structure, generic phrasing)
- Vary sentence length naturally (mix short and long)
- Add natural imperfections (contractions, casual connectors where appropriate)
- Keep the original meaning and key information intact
- Do NOT add any preamble, explanations, or meta-commentary
- Output ONLY the rewritten text, nothing else

Text to humanize:
${text}`;
        break;

      case 'detector':
        systemPrompt = 'You are an AI content detection expert. Analyze text and determine the likelihood it was generated by AI.';
        userPrompt = `Analyze the following text and determine if it was likely written by AI or a human.

Respond in this exact JSON format only:
{
  "score": <number 0-100 representing % likelihood of being AI-generated>,
  "verdict": "<Human Written | Likely Human | Mixed | Likely AI | AI Generated>",
  "reasons": ["<reason 1>", "<reason 2>", "<reason 3>"],
  "details": "<brief 1-2 sentence explanation>"
}

Text to analyze:
${text}`;
        break;

      case 'paraphraser':
        systemPrompt = 'You are an expert paraphrasing tool. You rewrite text while preserving the original meaning.';
        userPrompt = `Paraphrase the following text in a ${tone || 'standard'} tone.

Rules:
- Completely rewrite using different words and sentence structures
- Keep the original meaning 100% intact
- Match the requested tone
- Do NOT add any preamble or explanations
- Output ONLY the paraphrased text

Text to paraphrase:
${text}`;
        break;

      case 'meta-description':
        systemPrompt = 'You are an SEO expert specializing in meta descriptions and title tags.';
        userPrompt = `Generate SEO-optimized meta descriptions and title tags for the following page content or topic.

Respond in this exact JSON format only:
{
  "titles": [
    {"text": "<title tag 1, under 60 chars>", "chars": <character count>},
    {"text": "<title tag 2, under 60 chars>", "chars": <character count>},
    {"text": "<title tag 3, under 60 chars>", "chars": <character count>}
  ],
  "descriptions": [
    {"text": "<meta description 1, under 155 chars>", "chars": <character count>},
    {"text": "<meta description 2, under 155 chars>", "chars": <character count>},
    {"text": "<meta description 3, under 155 chars>", "chars": <character count>}
  ]
}

Page content/topic:
${text}`;
        break;

      case 'email-writer':
        systemPrompt = 'You are an expert business email writer.';
        userPrompt = `Write a professional email based on the following request.

Tone: ${tone || 'professional'}

Rules:
- Write a complete email with subject line, greeting, body, and sign-off
- Match the requested tone
- Keep it concise and actionable
- Format as:
Subject: <subject line>

<email body>

Request:
${text}`;
        break;

      default:
        return new Response(JSON.stringify({ error: 'Invalid tool type' }), {
          status: 400,
          headers: { 'Content-Type': 'application/json' },
        });
    }

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4000,
        system: systemPrompt,
        messages: [{ role: 'user', content: userPrompt }],
      }),
    });

    const data = await response.json();

    if (data.content && data.content[0]) {
      return new Response(JSON.stringify({ result: data.content[0].text }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    return new Response(JSON.stringify({ error: 'Failed to process text. Please try again.' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });

  } catch (err) {
    return new Response(JSON.stringify({ error: 'Server error. Please try again.' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
};
